# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
name: Fetch RSS feeds
on:
  rss:
    url: https://hnrss.org/newest?points=300&count=3
jobs:
  request:
    name: Make a HTTP Request
    runs-on: ubuntu-latest
    steps:
      - name: Make a HTTP Request
        uses: actionsflow/axios@v1
        with:
          url: https://hookb.in/VGPzxoWbdjtE22bwznzE
          method: POST
          body: |
            {
              "link":"${{ on.rss.outputs.link }}", 
              "title": "${{ on.rss.outputs.title }}",
              "content":"<<<${{ on.rss.outputs.contentSnippet }}>>>"
            }
